keys:
  - &admin age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

creation_rules:
  # Project admin
  - path_regex: ^project/secrets.yaml$
    key_groups:
      - age:
          - *admin
  # Production secrets
  - path_regex: ^infrastructure/environments/production/secrets.yaml$
    key_groups:
      - age:
          - *admin
  # Server admin key
  - path_regex: ^infrastructure/environments/production/admin-key$
    key_groups:
      - age:
          - *admin
